# SPDX-FileCopyrightText: 2020-2023 Gilles Caulier <caulier dot gilles at gmail dot com>
# SPDX-License-Identifier: CC0-1.0
#
# See targets available at https://invent.kde.org/sysadmin/ci-utilities/-/tree/master/gitlab-templates

include:
  - project: sysadmin/ci-utilities
    file:

      # --- CI Validators ---

      # - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/json-validation.yml

      # --- Continuous Integration Qt5 ---

      - /gitlab-templates/linux.yml
      # - /gitlab-templates/windows.yml
      # - /gitlab-templates/freebsd.yml

      # --- Continuous Integration Qt6 ---

      # - /gitlab-templates/linux-qt6.yml
      # - /gitlab-templates/craft-windows-x86-64.yml

      # --- Continuous Deployement Qt5 ---

      # - /gitlab-templates/flatpak.yml
      # - /gitlab-templates/craft-appimage.yml
      # - /gitlab-templates/craft-windows-appx-qt5.yml

      # --- Continuous Deployement Qt6 ---

suse_tumbleweed_qt515:
  stage: build
  script:
    - echo "GIT_CLONE_PROTECTION_ACTIVE=false" >> build.env
  artifacts:
    reports:
      dotenv: build.env
